const jobsSeedData = [
  {
    companyName: "AgroAI Innovations Pvt. Ltd.",
    jobRoleName: "AI / Machine Learning Engineer (Fresher)",
    description:
      "We are seeking an AI/ML Engineer Fresher with B.Tech in Artificial Intelligence and Machine Learning or Computer Science from Kongu Engineering College or similar institutions. Strong hands-on experience in Machine Learning, Deep Learning, Keras, TensorFlow, and Generative AI required. The candidate will work on real-world AI systems including smart agriculture platforms, smart farming assistants, crop disease detection using CNNs (Convolutional Neural Networks), plant disease classification, and predictive analytics for sustainable farming. Responsibilities include building ML pipelines using Python, Keras, and TensorFlow, developing FastAPI-based backends with REST APIs, integrating multilingual AI chatbots using NLP, Groq AI, Gemini API, and deploying scalable cloud-based solutions on Azure, AWS, Firebase. Experience with MongoDB, Firebase, NoSQL databases, REST APIs, Git, GitHub, Power BI, Tableau, and AI-driven decision support systems is highly desirable. Knowledge of image processing, computer vision, healthcare AI, autonomous vehicles, research publications in IEEE, and agricultural AI is a plus. Work on projects involving Gemini API, OpenAI, Groq AI integration, attendance monitoring systems, code to flowchart converters. Academic excellence and hackathon experience valued. Looking for candidates with CGPA 8.5+ and leadership roles in AI Coding Club or CSI.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–10 LPA",
    skills: [
      "Python",
      "Machine Learning",
      "Deep Learning",
      "Keras",
      "TensorFlow",
      "FastAPI",
      "Generative AI",
      "MongoDB",
      "Firebase",
      "Azure",
      "AWS",
      "REST APIs",
      "CNN",
      "Computer Vision",
      "NLP",
      "Git",
      "GitHub",
      "Groq AI",
      "Gemini API",
      "Power BI",
      "Tableau",
    ],
    explanation:
      "This role strongly aligns with experience in building an AI-powered smart farming assistant using CNNs, predictive analytics, and FastAPI. Cloud exposure, MongoDB usage, and applied ML projects make this an excellent match.",
  },
  {
    companyName: "FinTech Chain Systems Inc.",
    jobRoleName: "Software Engineer – AI & Data Systems (Graduate)",
    description:
      "We are hiring a Software Engineer with B.Tech in AI & ML or Computer Science from Kongu Engineering College or equivalent institutions. Background in AI, data engineering, and financial systems required. The role involves working on financial data models, implementing ACTUS-based workflows for financial contracts, ACTUS Framework documentation, ACTUS Quickstart guides using Docusaurus and Markdown for 200+ developers, and exploring privacy-preserving technologies such as Zero-Knowledge Proofs (ZK proofs) on MINA blockchain for secure financial workflows. The candidate will collaborate with global teams at ChainAim Technologies USA or similar companies using Git and GitHub, contribute to scalable backend systems in Python with FastAPI, work with cloud-native solutions using Azure, AWS, and manage databases like MongoDB and MySQL. Strong documentation skills, technical writing experience, developer onboarding expertise, and knowledge of blockchain technologies are valuable. Experience with financial data systems, data engineering pipelines, cloud deployment, and remote work is preferred. Candidates with contributions to open-source documentation, Kaggle datasets, and hackathon wins are highly valued. Microsoft Azure AI Engineer Associate certification is a plus.",
    location: "Remote",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹8–12 LPA",
    skills: [
      "Python",
      "Financial Data Systems",
      "ACTUS Framework",
      "Docusaurus",
      "Azure",
      "AWS",
      "ZK Proofs",
      "GitHub",
      "Git",
      "Data Engineering",
      "MongoDB",
      "MySQL",
      "FastAPI",
      "Blockchain",
      "Technical Writing",
      "MINA",
      "Markdown",
    ],
    explanation:
      "This role directly mirrors experience at ChainAim Technologies, including ACTUS documentation, Docusaurus usage, financial workflows, and cloud-based development.",
  },
  {
    companyName: "HealthVision AI Labs",
    jobRoleName: "Deep Learning Research Engineer (Entry Level)",
    description:
      "We are looking for a Deep Learning Research Engineer with B.Tech in AI & ML from Kongu Engineering College or similar institutions with strong academic performance (CGPA 8.5+). Strong academic and practical experience in image processing, CNNs (Convolutional Neural Networks), interpretable AI, and explainable AI required. The candidate will work on healthcare AI applications including enhanced early identification of autism spectrum disorder using deep learning and advanced ML, autonomous system applications including interpretable image processing for autonomous vehicles within industry premises, develop deep learning models for medical image analysis, leveraging deep learning for comprehensive plant disease classification for sustainable agriculture, and contribute to research publications in IEEE conferences and book chapters in Distributed Deep Learning and Explainable AI (XAI) in Industry 4.0. Experience with Python, Keras, TensorFlow, and research-driven development is essential. Knowledge of autonomous vehicles, healthcare AI systems including autism spectrum disorder detection, agricultural AI for plant disease classification, and deep learning architectures is highly valued. Familiarity with Git, GitHub, cloud platforms (Azure, AWS), dataset management, and training neural networks is required. Looking for candidates with multiple IEEE publications, book chapters, and academic excellence awards.",
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–11 LPA",
    skills: [
      "Python",
      "Deep Learning",
      "CNN",
      "Image Processing",
      "Explainable AI",
      "Keras",
      "TensorFlow",
      "Research & Publications",
      "Computer Vision",
      "Healthcare AI",
      "Autonomous Vehicles",
      "IEEE Publications",
      "Git",
      "GitHub",
      "Plant Disease Classification",
      "Autism Spectrum Disorder",
      "XAI",
    ],
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–11 LPA",
    skills: [
      "Python",
      "Deep Learning",
      "CNN",
      "Image Processing",
      "Explainable AI",
      "Keras",
      "TensorFlow",
      "Research & Publications",
      "Computer Vision",
      "Healthcare AI",
      "Autonomous Vehicles",
      "IEEE Publications",
      "Git",
      "GitHub",
    ],
    explanation:
      "This role aligns with multiple IEEE publications, deep learning research in healthcare and autonomous vehicles, and hands-on CNN-based model development.",
  },
  {
    companyName: "SmartHire Technologies",
    jobRoleName: "Frontend Engineer – AI Platforms (Graduate)",
    description:
      "We are seeking a Frontend Engineer with B.Tech in AI & ML or Computer Science from Kongu Engineering College or equivalent to build AI-powered recruitment platforms, HR platforms, and interview automation systems using modern web technologies similar to Shinelogics projects. Responsibilities include developing responsive UIs using React, JavaScript, and Tailwind CSS for recruitment platforms, integrating AI APIs (Groq AI for smart interview query handling, OpenAI, Gemini API, Mistral AI) for resume parsing, chatbot interfaces, streamlining resume processing and scheduling, and interview automation, and collaborating with backend teams working with FastAPI, MongoDB, Node.js, and cloud platforms. The candidate should have experience building production-ready dashboards, workflow automation boosting HR workflow efficiency by 50%, attendance monitoring systems for 700+ students like AttendanceSync with JWT authentication and RBAC, and improving efficiency through intelligent UI design. Knowledge of Git, GitHub, REST API integration, state management in React, email automation with Nodemailer, and deployment on Render or cloud platforms is essential. Experience with AI-powered applications, recruitment platforms, attendance systems, smart product management chatbots reducing manual effort by 65%, or automation tools is highly desirable. Hackathon winners and candidates with leadership in AI Coding Club preferred.",
    location: "Chennai, Tamil Nadu",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹6–9 LPA",
    skills: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "AI API Integration",
      "Frontend Development",
      "GitHub",
      "Git",
      "Groq AI",
      "OpenAI",
      "Gemini API",
      "REST APIs",
      "MongoDB",
      "FastAPI",
      "Node.js",
      "JWT",
      "RBAC",
      "Nodemailer",
      "Mistral AI",
    ],
    explanation:
      "This role maps closely to frontend development experience at Shinelogics, including AI-powered recruitment platforms and workflow optimization.",
  },
  {
    companyName: "CloudData Analytics Pvt. Ltd.",
    jobRoleName: "Data Engineer – Cloud & Automation (Fresher)",
    description:
      "We are hiring a Data Engineer with B.Tech in AI & ML or Computer Science from Kongu Engineering College or similar institutions to automate large-scale data extraction from 100+ sources, build cloud security tools, Python-based vulnerability scanners for Azure improving security checks by 30%, and develop Python-based automation systems similar to Centillion Labs projects. The role involves working with Selenium for web automation, BeautifulSoup for web scraping and data extraction, cloud platforms like Azure and AWS for deployment and security, and developing Python scripts to improve data quality, system security, and automation workflows. Strong problem-solving skills, cloud exposure, Microsoft Azure AI Engineer Associate certification, and experience with databases (MongoDB, MySQL) are required. Familiarity with Git, GitHub, REST APIs, data engineering pipelines, ETL processes, cloud security best practices, Azure security tools, automation frameworks, and data validation is essential. Experience with Tech Companies Global Dataset contributions on Kaggle enabling insights into global company trends, Power BI, Tableau for data analysis, and remote work experience is highly valued. MongoDB Certified Associate Developer certification is a plus. Candidates with academic excellence awards and hackathon experience preferred.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–10 LPA",
    skills: [
      "Python",
      "Data Engineering",
      "Selenium",
      "BeautifulSoup",
      "Azure",
      "AWS",
      "Cloud Security",
      "Automation",
      "MongoDB",
      "MySQL",
      "Git",
      "GitHub",
      "Web Scraping",
      "ETL",
      "Power BI",
      "Tableau",
      "Kaggle",
      "Azure AI Engineer",
    ],
    explanation:
      "This role directly aligns with data engineering experience at Centillion Labs, including automation, scraping, and Azure-based security tooling.",
  },
  {
    companyName: "NLP Innovators Pvt. Ltd.",
    jobRoleName: "NLP Engineer – Chatbot & Voice AI (Fresher)",
    description:
      "We are seeking an NLP Engineer from Kongu Engineering College with B.Tech in AI & ML to build multilingual AI chatbots, voice-enabled assistants, and NLU systems. Work on smart farming assistants with Groq API chatbot integration, multilingual voice support, natural language CRUD operations for product management chatbots like Farmlink-Bot, and NLP-based interview query handling. Responsibilities include integrating Groq AI, Mistral AI, Gemini API, OpenAI for chatbot development, implementing voice recognition and multilingual support, building conversational AI for recruitment and agriculture platforms, and deploying on Firebase, MongoDB. Experience with Python, FastAPI, React, Tailwind CSS, natural language understanding, session management, and reducing manual effort by 65% through automation is required. Knowledge of calendar API integration, task planning automation, and AI-powered decision support systems valued. Hackathon winners from KEC Hackathon'24, KEC Hackathon'25, or SIH preferred.",
    location: "Pune, Maharashtra",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–11 LPA",
    skills: [
      "Python",
      "NLP",
      "Groq AI",
      "Mistral AI",
      "Gemini API",
      "FastAPI",
      "MongoDB",
      "Firebase",
      "Multilingual AI",
      "Chatbots",
      "Voice AI",
      "React",
      "Tailwind CSS",
    ],
    explanation:
      "Perfect match for smart farming assistant and product management chatbot projects with multilingual AI and Groq API integration.",
  },
  {
    companyName: "Blockchain Solutions India",
    jobRoleName: "Blockchain Developer – ZK & Smart Contracts (Entry Level)",
    description:
      "Hiring Blockchain Developer from Kongu Engineering College with B.Tech in AI & ML or CS. Work on Zero-Knowledge Proofs (ZK proofs) on MINA blockchain for secure financial workflows, privacy-preserving technologies, ACTUS Framework implementation for financial contracts, and smart contract development. Experience at ChainAim Technologies USA or similar remote blockchain companies valued. Responsibilities include exploring cryptographic protocols, implementing ZK-SNARKs, building decentralized applications, documenting blockchain systems using Docusaurus and Markdown, and collaborating with global teams using Git and GitHub. Knowledge of Python, financial data systems, cloud deployment on Azure/AWS, and technical writing for developer onboarding is essential. Candidates with contributions to actus-userguides documentation, open-source blockchain projects, and hackathon wins highly preferred.",
    location: "Remote",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹9–14 LPA",
    skills: [
      "Blockchain",
      "ZK Proofs",
      "MINA",
      "ACTUS Framework",
      "Smart Contracts",
      "Python",
      "Docusaurus",
      "Git",
      "GitHub",
      "Technical Writing",
      "Cryptography",
    ],
    explanation:
      "Direct match with ChainAim Technologies experience in ZK proofs, MINA blockchain, and ACTUS documentation.",
  },
  {
    companyName: "CodeViz Technologies",
    jobRoleName:
      "Software Developer – Code Analysis & Visualization (Graduate)",
    description:
      "Seeking Software Developer from Kongu Engineering College to build code analysis tools, flowchart generators, and developer productivity platforms. Work on Code2Logic: Code to Flowchart Converter using Gemini API, Python graph logic, modular parsing techniques, converting code into pseudocode and flowcharts, and improving code review efficiency by 50%. Responsibilities include developing web applications with HTML, CSS, JavaScript, integrating AI APIs (Gemini API, OpenAI), building visualization tools, and creating developer tools. Experience with Python, FastAPI, React, algorithm visualization, and academic projects from KEC is valued. Knowledge of graph algorithms, parsing techniques, AST manipulation, and code analysis is essential. Candidates with 1st Prize in KEC Hackathon'25 or SIH Internal Hackathon preferred.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹6–9 LPA",
    skills: [
      "Python",
      "JavaScript",
      "Gemini API",
      "HTML",
      "CSS",
      "Code Analysis",
      "Graph Algorithms",
      "FastAPI",
      "React",
      "Visualization",
    ],
    explanation:
      "Perfect match for CodeToFlow project with Gemini API, Python graph logic, and code analysis experience.",
  },
  {
    companyName: "AgriTech Innovations",
    jobRoleName: "ML Engineer – Agriculture & Sustainability (Fresher)",
    description:
      "Hiring ML Engineer from Kongu Engineering College with B.Tech in AI & ML for agricultural AI systems, sustainable farming solutions, and plant disease classification. Work on leveraging deep learning for comprehensive plant disease classification (IEEE Mar 2025 publication), CNN-based crop disease detection, predictive analytics for farming, smart agriculture platforms like Farmora, and ML-based crop advisory systems. Responsibilities include building multimodal AI systems, implementing CNN disease detection models using Keras and TensorFlow, developing FastAPI backends, integrating Firebase and MongoDB, and deploying on Azure/AWS. Experience with computer vision, image processing, agricultural datasets, research publications in IEEE, and academic excellence awards valued. Knowledge of Groq AI chatbot integration, calendar APIs for task planning, and predictive analytics essential.",
    location: "Coimbatore, Tamil Nadu",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–10 LPA",
    skills: [
      "Python",
      "Machine Learning",
      "CNN",
      "Keras",
      "TensorFlow",
      "FastAPI",
      "Computer Vision",
      "Agriculture AI",
      "Plant Disease Classification",
      "MongoDB",
      "Firebase",
      "Azure",
      "IEEE Publications",
    ],
    explanation:
      "Excellent match for Farmora project and IEEE publication on plant disease classification using deep learning.",
  },
  {
    companyName: "HealthAI Research Labs",
    jobRoleName: "AI Researcher – Healthcare & Medical Imaging (Entry Level)",
    description:
      "Seeking AI Researcher from Kongu Engineering College with B.Tech in AI & ML for healthcare AI applications, medical imaging analysis, and autism spectrum disorder detection. Work on Enhanced Early Identification of Autism Spectrum Disorder using Deep Learning and Advanced ML (IEEE Dec 2024), CNN-based medical image analysis, explainable AI (XAI) for healthcare, and interpretable deep learning models. Responsibilities include developing deep learning architectures using Python, Keras, TensorFlow, publishing research in IEEE conferences, contributing to book chapters in Distributed Deep Learning and XAI in Industry 4.0, and collaborating on healthcare AI systems. Strong academic performance (CGPA 8.5+), multiple research publications, and experience with image processing, computer vision, model interpretability valued. Git, GitHub, Azure, AWS familiarity required.",
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹8–12 LPA",
    skills: [
      "Python",
      "Deep Learning",
      "CNN",
      "Healthcare AI",
      "Keras",
      "TensorFlow",
      "Explainable AI",
      "Medical Imaging",
      "IEEE Publications",
      "XAI",
      "Research",
      "Autism Detection",
    ],
    explanation:
      "Perfect match for IEEE publication on autism spectrum disorder detection and healthcare AI research.",
  },
  {
    companyName: "Autonomous Systems Corp.",
    jobRoleName: "Computer Vision Engineer – Autonomous Vehicles (Graduate)",
    description:
      "Hiring Computer Vision Engineer from Kongu Engineering College for autonomous vehicles, interpretable image processing, and Industry 4.0 applications. Work on Interpretable Image Processing for Autonomous Vehicles within Industry Premises (Book Chapter 2024), developing CNN-based perception systems, implementing explainable AI for safety-critical applications, and building deep learning models for vehicle automation. Responsibilities include image processing using Python, Keras, TensorFlow, developing real-time computer vision systems, contributing to research publications, and deploying on cloud platforms (Azure, AWS). Experience with autonomous vehicle datasets, XAI techniques, book chapter publications in Industry 4.0, and academic excellence required. Knowledge of CNN architectures, object detection, semantic segmentation, and Git/GitHub essential.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹9–13 LPA",
    skills: [
      "Python",
      "Computer Vision",
      "CNN",
      "Deep Learning",
      "Autonomous Vehicles",
      "Keras",
      "TensorFlow",
      "Explainable AI",
      "Image Processing",
      "Industry 4.0",
      "Research Publications",
    ],
    explanation:
      "Direct match for book chapter on interpretable image processing for autonomous vehicles and Industry 4.0.",
  },
  {
    companyName: "EduTech Platforms India",
    jobRoleName: "Full Stack Developer – Educational Systems (Fresher)",
    description:
      "Seeking Full Stack Developer from Kongu Engineering College with B.Tech in AI & ML for attendance monitoring systems, student management platforms, and educational automation. Work on AttendanceSync-like systems for 700+ students, implementing JWT authentication, RBAC (Role-Based Access Control), email automation with Nodemailer, and web applications for faculty and staff. Responsibilities include React frontend development with Tailwind CSS, Node.js backend with MongoDB, REST API development, deploying on Render or cloud platforms, and reducing manual effort by 70% through automation. Experience with full-stack MERN development, authentication systems, role-based access, and tracking accuracy improvements valued. Knowledge of JavaScript, Git, GitHub, and hackathon experience (KEC Hackathon'24/25) preferred.",
    location: "Chennai, Tamil Nadu",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹6–9 LPA",
    skills: [
      "React",
      "Node.js",
      "MongoDB",
      "JavaScript",
      "Tailwind CSS",
      "JWT",
      "RBAC",
      "Nodemailer",
      "REST APIs",
      "Full Stack",
      "Render",
      "Git",
      "GitHub",
    ],
    explanation:
      "Perfect match for AttendanceSync project with JWT, RBAC, Nodemailer, and 70% manual effort reduction.",
  },
  {
    companyName: "DataViz Analytics",
    jobRoleName: "Business Intelligence Developer (Entry Level)",
    description:
      "Hiring BI Developer from Kongu Engineering College with B.Tech in AI & ML for data visualization, analytics dashboards, and business intelligence solutions. Work with Power BI, Tableau for creating insights dashboards, analyzing Tech Companies Global Dataset on Kaggle, enabling global company trend comparisons, and building data-driven decision support systems. Responsibilities include ETL pipeline development, database management with MongoDB and MySQL, Python data analysis with Pandas, creating interactive visualizations, and cloud deployment on Azure/AWS. Experience with data engineering, Kaggle dataset contributions (Dec 2024), and remote work valued. Knowledge of data quality improvement, automation workflows, and Git/GitHub required. Academic excellence and leadership in AI Coding Club or CSI preferred.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–11 LPA",
    skills: [
      "Power BI",
      "Tableau",
      "Python",
      "Pandas",
      "MongoDB",
      "MySQL",
      "Kaggle",
      "ETL",
      "Azure",
      "AWS",
      "Data Visualization",
      "Git",
    ],
    explanation:
      "Excellent match for Kaggle dataset contribution and Power BI/Tableau data analysis skills.",
  },
  {
    companyName: "CloudSec Technologies",
    jobRoleName: "Cloud Security Engineer – Azure (Fresher)",
    description:
      "Seeking Cloud Security Engineer from Kongu Engineering College with Microsoft Azure AI Engineer Associate certification for building Azure security tools, vulnerability scanners, and cloud automation systems. Work on Python-based vulnerability scanner for Azure improving security checks by 30%, cloud security best practices, Azure security tools development, and automation frameworks similar to Centillion Labs projects. Responsibilities include developing security automation using Python, Selenium, implementing cloud security monitoring, managing Azure deployments, and working with MongoDB, MySQL databases. Experience with web scraping (BeautifulSoup), data extraction from 100+ sources, ETL processes, and remote work at Centillion Labs valued. Knowledge of AWS, Git, GitHub, REST APIs, and data validation essential. MongoDB Certified Associate Developer certification is a plus.",
    location: "Remote",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹8–12 LPA",
    skills: [
      "Azure",
      "Python",
      "Cloud Security",
      "Selenium",
      "BeautifulSoup",
      "MongoDB",
      "MySQL",
      "Azure AI Engineer",
      "Automation",
      "AWS",
      "Git",
      "GitHub",
    ],
    explanation:
      "Perfect match for Centillion Labs experience with Azure security tools, vulnerability scanners, and 30% security improvement.",
  },
  {
    companyName: "AI Recruitment Solutions",
    jobRoleName: "AI Integration Engineer – HR Tech (Graduate)",
    description:
      "Hiring AI Integration Engineer from Kongu Engineering College for recruitment platforms, resume parsing systems, and HR workflow automation. Build AI-powered recruitment platforms like Shinelogics projects using React, integrating Groq AI for smart interview query handling, streamlining resume processing and scheduling, and boosting HR workflow efficiency by 50%. Responsibilities include React and Tailwind CSS development, FastAPI backend integration, MongoDB database management, AI API integration (Groq AI, Gemini API, OpenAI), and deploying on cloud platforms. Experience with production-ready dashboards, workflow automation, attendance systems, and reducing manual effort through intelligent design valued. Knowledge of Node.js, JavaScript, REST APIs, Git, GitHub, and hackathon wins (KEC Hackathon'25 1st Prize) essential.",
    location: "Chennai, Tamil Nadu",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–10 LPA",
    skills: [
      "React",
      "Groq AI",
      "FastAPI",
      "MongoDB",
      "Tailwind CSS",
      "JavaScript",
      "AI API Integration",
      "Node.js",
      "Gemini API",
      "OpenAI",
      "REST APIs",
      "Git",
      "GitHub",
    ],
    explanation:
      "Direct match for Shinelogics recruitment platform with Groq AI integration and 50% efficiency improvement.",
  },
  {
    companyName: "Firebase Experts India",
    jobRoleName: "Backend Developer – Firebase & NoSQL (Fresher)",
    description:
      "Seeking Backend Developer from Kongu Engineering College with B.Tech in AI & ML for Firebase, MongoDB, and NoSQL database systems. Work on smart product management chatbots like Farmlink-Bot with Firebase sessions, natural language CRUD operations, inventory tracking automation reducing manual effort by 65%, and scalable cloud-based solutions. Responsibilities include FastAPI backend development, MongoDB and Firebase database management, REST API design, implementing session management, and deploying on Firebase, Azure, AWS. Experience with Python, Mistral AI, React frontends, Tailwind CSS, and automation tools valued. Knowledge of NoSQL databases, cloud deployment, Git, GitHub, and multilingual AI integration essential. Academic excellence (CGPA 8.79) and leadership roles in AI Coding Club preferred.",
    location: "Bangalore, Karnataka",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹7–10 LPA",
    skills: [
      "Firebase",
      "MongoDB",
      "Python",
      "FastAPI",
      "NoSQL",
      "Mistral AI",
      "React",
      "Tailwind CSS",
      "REST APIs",
      "Azure",
      "AWS",
      "Git",
      "GitHub",
    ],
    explanation:
      "Perfect match for Farmlink-Bot project with Firebase sessions, MongoDB, and 65% manual effort reduction.",
  },
  {
    companyName: "DevOps Cloud Solutions",
    jobRoleName: "DevOps Engineer – Cloud Automation (Entry Level)",
    description:
      "Hiring DevOps Engineer from Kongu Engineering College with Microsoft Azure AI Engineer Associate certification for cloud automation, CI/CD pipelines, and deployment workflows. Work with Azure, AWS cloud platforms, Git and GitHub for version control, deploying scalable applications on Render or cloud services, and automating infrastructure provisioning. Responsibilities include managing MongoDB, MySQL databases in cloud environments, implementing REST APIs, developing Python automation scripts, and working with FastAPI, Node.js backends. Experience with remote work, technical documentation using Docusaurus and Markdown, and global team collaboration valued. Knowledge of Docker, Kubernetes, cloud security, and ETL processes essential. Candidates with contributions to open-source projects and hackathon experience preferred.",
    location: "Remote",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹8–12 LPA",
    skills: [
      "Azure",
      "AWS",
      "Git",
      "GitHub",
      "Python",
      "DevOps",
      "CI/CD",
      "MongoDB",
      "MySQL",
      "FastAPI",
      "Node.js",
      "Render",
      "Automation",
    ],
    explanation:
      "Good match for cloud deployment experience across Azure, AWS, Render with Git/GitHub expertise.",
  },
  {
    companyName: "Research Publications Group",
    jobRoleName: "Research Associate – AI & Deep Learning (Graduate)",
    description:
      "Seeking Research Associate from Kongu Engineering College with multiple IEEE publications and book chapters for continuing research in AI, deep learning, and explainable AI. Work on publishing research papers like Enhanced Early Identification of Autism Spectrum Disorder using Deep Learning (IEEE Dec 2024), Interpretable Image Processing for Autonomous Vehicles (Book Chapter 2024), Leveraging Deep Learning for Plant Disease Classification (IEEE Mar 2025), and contributing to Distributed Deep Learning and XAI in Industry 4.0 book. Responsibilities include developing deep learning models using Python, Keras, TensorFlow, conducting experiments on healthcare AI, autonomous vehicles, agriculture AI, writing technical papers, and presenting at conferences. Strong academic performance (CGPA 8.79), Academic Excellence Award (2023-2024), and publication track record essential. Knowledge of CNN, computer vision, image processing, Git, GitHub required.",
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹8–13 LPA",
    skills: [
      "Python",
      "Deep Learning",
      "Keras",
      "TensorFlow",
      "CNN",
      "IEEE Publications",
      "Research",
      "Healthcare AI",
      "Autonomous Vehicles",
      "Agriculture AI",
      "XAI",
      "Academic Writing",
    ],
    explanation:
      "Perfect match for multiple IEEE publications, book chapters, and research excellence in AI/ML.",
  },
  {
    companyName: "Generative AI Labs",
    jobRoleName: "Generative AI Developer (Fresher)",
    description:
      "Hiring Generative AI Developer from Kongu Engineering College with B.Tech in AI & ML for building generative AI applications, LLM integration, and AI-powered tools. Work with Gemini API, Groq AI, OpenAI, Mistral AI for chatbot development, code generation, flowchart conversion, resume parsing, and intelligent automation. Responsibilities include developing FastAPI backends, integrating multiple AI APIs, building React frontends with Tailwind CSS, and deploying on Firebase, Azure, AWS. Experience with Python, machine learning pipelines, NLP, multilingual AI, and reducing manual effort through AI automation valued. Knowledge of prompt engineering, fine-tuning LLMs, MongoDB, Git, GitHub essential. Hackathon winners from KEC Hackathon'25 (1st Prize), KEC Hackathon'24 (1st Prize), or SIH Internal Hackathon preferred.",
    location: "Pune, Maharashtra",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹9–14 LPA",
    skills: [
      "Generative AI",
      "Gemini API",
      "Groq AI",
      "OpenAI",
      "Mistral AI",
      "Python",
      "FastAPI",
      "React",
      "NLP",
      "MongoDB",
      "Firebase",
      "Tailwind CSS",
    ],
    explanation:
      "Excellent match for multiple projects using Gemini API, Groq AI integration, and AI-powered automation.",
  },
  {
    companyName: "Tech Leadership Academy",
    jobRoleName: "Technical Lead – Student Organizations (Entry Level)",
    description:
      "Seeking Technical Lead from Kongu Engineering College with proven leadership in student organizations like AI Coding Club and CSI for mentoring junior students, organizing hackathons, and technical events. Responsibilities include leading technical teams as Joint Secretary of AI Coding Club (2024-2025), organizing coding competitions, mentoring 200+ students, coordinating with Executive Members, and representing college at technical events. Experience winning 1st Prize in KEC Hackathon'25 (30 hrs), KEC Hackathon'24 (30 hrs), SIH Internal Hackathon (2024), and Academic Excellence Award (2023-2024) essential. Work on building AI/ML projects, conducting workshops on Python, React, FastAPI, MongoDB, and promoting technical culture. Knowledge of project management, team coordination, event organization, and technical mentorship valued. Strong academic performance (CGPA 8.79) required.",
    location: "Perundurai, Tamil Nadu",
    type: "Full-time",
    experience: "0–1 years",
    salary: "₹6–9 LPA",
    skills: [
      "Leadership",
      "Team Management",
      "Technical Mentorship",
      "Python",
      "AI/ML",
      "Hackathon Organization",
      "Event Management",
      "Project Coordination",
    ],
    explanation:
      "Perfect match for leadership roles in AI Coding Club, CSI, and multiple hackathon victories.",
  },
];
export default jobsSeedData;
